# Generated by Django 5.2.1 on 2026-05-13 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('doc_pic', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category_pic', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=250)),
                ('patient_age', models.IntegerField()),
                ('appointment_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatientservice.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpatientservice.service'),
        ),
    ]
